name: Build (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Vet
      run: go vet -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build -v ./cmd/renderobject.go

    - name: Create artifact dir
      run: mkdir output
    
    - name: Move artifacts
      run: |
        move renderobject.exe output
        move README.md output
        move files output

    - uses: actions/upload-artifact@v4
      with:
        name: gorender-windows
        path: output/*
